[theme]

# Primary accent for interactive elements
primaryColor = '#ed145c'

# Background color for the main content area
backgroundColor = '#303233'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#969293'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = 'sans serif'



